# Matrices and Linear algebra

## PLU decomposition

In [32]:
import numpy as np

In [2]:
import scipy.linalg as LA

In [3]:
A = np.array([[2,1,1],[4,3,3],[8,7,9]]); A

array([[2, 1, 1],
       [4, 3, 3],
       [8, 7, 9]])

In [4]:
P,L,U = LA.lu(A)

Python has it as A=PLU, different from my notes, most textbooks and Matlab.

In [5]:
print(L);print(U)

[[1.         0.         0.        ]
 [0.25       1.         0.        ]
 [0.5        0.66666667 1.        ]]
[[ 8.          7.          9.        ]
 [ 0.         -0.75       -1.25      ]
 [ 0.          0.         -0.66666667]]


In [6]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

## Simple matrix operations

Define a random matrix

In [33]:
RandMat = np.random.randn(3,3)

In [34]:
RandMat

array([[ 0.31600967, -0.07842557, -0.04663752],
       [-0.14282635,  0.30928247, -0.33244316],
       [ 0.13847308,  0.90982736, -1.29372912]])

Taking certain entries/rows/columns of a matrix

In [35]:
A = RandMat

In [36]:
A[0,:] #first row

array([ 0.31600967, -0.07842557, -0.04663752])

In [37]:
A[:,0] # first column

array([ 0.31600967, -0.14282635,  0.13847308])

In [38]:
A[0,0]

0.31600966801159375

In [39]:
A[0:2,0:2]

array([[ 0.31600967, -0.07842557],
       [-0.14282635,  0.30928247]])

In [40]:
A[:2,:2]

array([[ 0.31600967, -0.07842557],
       [-0.14282635,  0.30928247]])

In [41]:
A[1:,1:]

array([[ 0.30928247, -0.33244316],
       [ 0.90982736, -1.29372912]])

So you can perform row operations in python

In [42]:
A[0,:]*2 + A[1,:]

array([ 0.48919299,  0.15243132, -0.4257182 ])

A vector/matrix of all 1's

In [43]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

A matrix of all 0's

In [12]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [44]:
np.eye(3)  # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Matrix product

In [45]:
B = np.ones([2,3]);B

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
C = np.array([[2,3],[1,1],[5,0]]);C

array([[2, 3],
       [1, 1],
       [5, 0]])

In [47]:
B@C   # matrix multiplication

array([[8., 4.],
       [8., 4.]])

In [49]:
D = C.T;D

array([[2, 1, 5],
       [3, 1, 0]])

In [50]:
B*D  #pointwise multiplication

array([[2., 1., 5.],
       [3., 1., 0.]])

In [51]:
C**2

array([[ 4,  9],
       [ 1,  1],
       [25,  0]])

Solve a linear system

In [52]:
A

array([[ 0.31600967, -0.07842557, -0.04663752],
       [-0.14282635,  0.30928247, -0.33244316],
       [ 0.13847308,  0.90982736, -1.29372912]])

In [54]:
b = np.random.randn(3);b

array([0.59588273, 1.57270739, 0.22183594])

In [55]:
x = np.linalg.solve(A,b);x  #solve Ax=b

array([ 58.58672961, 158.54183333, 117.59536385])

check if two arrays are equal

In [56]:
np.allclose(x,np.array([59,159,118]))

False

time it

In [57]:
import timeit

In [58]:
start = timeit.default_timer()
A = np.random.randn(1000,1000) #the operation that's being timed
end = timeit.default_timer()
time = end - start

In [59]:
time

0.03852928899868857

In [60]:
for i in range(5):
    print(i)

0
1
2
3
4


In [62]:
for i in range(5,2,-1):
    print(i)

5
4
3


In [63]:
for i in range(5,-1,-1):
    print(i)

5
4
3
2
1
0
